# need to remove the old configmap and add this one
# get the api token here (Bot User OAuth Token): https://api.slack.com/apps/A06FH32JZBR/oauth?

# kubectl delete configmap -n monitoring alertmanager
# apply the new config
# kubectl rollout restart statefulset -n monitoring alertmanager

# replace <paste token here>
apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: slack-notifications
      slack_configs:
      - api_url: https://slack.com/api/chat.postMessage
        channel: '#monitoring'
        http_config:
          authorization:
            credentials: <paste token here>
        send_resolved: true
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: slack-notifications
      repeat_interval: 3h
    templates:
    - /etc/alertmanager/*.tmpl
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: alertmanager
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.26.0
    helm.sh/chart: alertmanager-1.7.0
    helm.toolkit.fluxcd.io/name: alertmanager
    helm.toolkit.fluxcd.io/namespace: monitoring
  name: alertmanager
  namespace: monitoring
