apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sync.yaml
- alertmanagerConfigCustomResourceDefinition.yaml
- alertmanagerCustomResourceDefinition.yaml
- podmonitorCustomResourceDefinition.yaml
- probeCustomResourceDefinition.yaml
- prometheusCustomResourceDefinition.yaml
- prometheusruleCustomResourceDefinition.yaml
- servicemonitorCustomResourceDefinition.yaml
- thanosrulerCustomResourceDefinition.yaml