apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:
      valueFrom:
        jsonPath: '{.stringData.cloudflare-email}'
        secretKeyRef:
          name: cloudflare-email-secret
          key: cloudflare-email
          namespace: cert-manager
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email:
              valueFrom:
                jsonPath: '{.stringData.cloudflare-email}'
                secretKeyRef:
                  name: cloudflare-email-secret
                  key: cloudflare-email
                  namespace: cert-manager
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
          - ryanschnabel.com
          - '*.ryanschnabel.com'
