apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:
      secretKeyRef:
        name: cloudflare-email-secret
        key: cloudflare-email
        namespace: cert-manager
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email:
              secretKeyRef:
                name: cloudflare-email-secret
                key: cloudflare-email
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
              namespace: cert-manager
        selector:
          dnsZones:
          - ryanschnabel.com
          - '*.ryanschnabel.com'