apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/gitops-server
      version: 4.0.36
      sourceRef:
        kind: GitRepository
        name: weave-gitops
        namespace: flux-system
  interval: 1m
  values:
    metrics: 
      enabled: true
    adminUser:
      create: true
      username: schniebel
      passwordHash: $2a$10$qUdCHk68GLqkZQ3oP8hO7OblOkgPkOE2MJ9rGOlPKLc96gkN2ss3O