apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  chart:
    spec:
      chart: ./helm/oauth2-proxy
      version: 6.18.1
      sourceRef:
        kind: GitRepository
        name: oauth2-proxy
        namespace: flux-system
  interval: 1m
  values:
    nodeSelector:
      kubernetes.io/hostname: slave1
    image:
      tag: v7.5.1-arm64
    config:
      existingSecret: oauth2-proxy
    extraArgs:
      provider: "google"
      reverse-proxy: "true"