apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/plexinc/pms-docker
  ref:
    branch: master