apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: ./charts/longhorn
      version:  1.5.3
      sourceRef:
        kind: GitRepository
        name: longhorn
        namespace: flux-system
  interval: 1h