apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-bff
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-bff
  template:
    metadata:
      labels:
        app: admin-bff
    spec:
      containers:
      - name: admin-bff
        image: schniebel/admin-bff:729472d58196697893267fce4aed4cfa4219f5be
        ports:
        - containerPort: 80