apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  chart:
    spec:
      chart: ./charts/plex-media-server
      version: 0.1.8
      sourceRef:
        kind: GitRepository
        name: plex
        namespace: flux-system
  interval: 1m
  values:
    pms:
      storageClassName: longhorn
      configStorage: 5Gi
    extraVolumeMounts:
      - mountPath: /mnt/nfs-test
        name: nfs-test
    extraVolumes:
      - name: nfs-test
        persistentVolumeClaim:
        claimName: nfs-test
    extraEnv:
      PLEX_CLAIM: "claim-zLkQCw4GkvgJpyR241bT"