apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-forward-auth
    - name: kube-prometheus
  interval: 1m
  path: ./clusters/default/monitoring/ingress
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m