apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-db-nfs-pvc
  namespace: monitoring
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
