apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-setup
  interval: 1m
  path: ./clusters/default/monitoring/kube-prometheus/manifests/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m