kubectl create secret generic cluster-user-auth \
  --namespace flux-system \
  --from-literal=username=schniebel \
  --from-literal=password='<password>'


apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth
    namespace: flux-system
stringData:
    clientID: <your-client-id>
    clientSecret: <your-client-secret> 
    issuerURL: https://accounts.google.com
    redirectURL: https://flux.ryanschnabel.com/oauth2/callback
    customScopes: openid,email