apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api-service-account 
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
      - name: api
        image: schniebel/ryanschnabel-api:605d890e80ce181bc3b2247257b154f635b81c4c
        ports:
        - containerPort: 8080
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key-secret
              key: API_KEY
        - name: SECRET_NAME
          value: "whitelist-secret"
        - name: SECRET_NAMESPACE
          value: "traefik-forward-auth"
        - name: SECRET_DATA_KEY
          value: "whitelist"
        - name: SECRET_NAME
          value: "whitelist-secret"
        - name: DEPLOYMENT_NAME
          value: "traefik-forward-auth"
        - name: DEPLOYMENT_NAMESPACE
          value: "traefik-forward-auth""