apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
      - name: api
        image: schniebel/ryanschnabel-api:d38dc6eb037e4ee60b15d4fa19a9494ebc98def2
        ports:
        - containerPort: 8080