apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
      - name: api
        image: schniebel/ryanschnabel-api:7767947fbde3b0315c70556074a3bf7db76e4c44
        ports:
        - containerPort: 8080