apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: api

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: secret-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: api
subjects:
- kind: ServiceAccount
  name: api-service-account
  namespace: api
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
