apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: ./deploy/charts/rook-ceph
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: rook-ceph
        namespace: flux-system
  interval: 1m
  values:
    image:
      tag: v1.13.0.178.gf6cadd548
    monitoring:
      enabled: true