apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kubernetes-sigs
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
  ref:
    branch: master