apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-static-provisioner
  namespace: local-static-provisioner
spec:
  chart:
    spec:
      chart: ./helm/provisioner
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: kubernetes-sigs
        namespace: flux-system
  interval: 1h
  values:
    nodeSelector:
      kubernetes.io/hostname: slave1