apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/weaveworks/weave-gitops
  ref:
    branch: main