apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  chart:
    spec:
      chart: ./charts/gitops-server
      version: 4.0.36
      sourceRef:
        kind: GitRepository
        name: longhorn-system
        namespace: flux-system
  interval: 1m