apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ryanschnabel-com
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ryanschnabel-com
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^\d+$'