apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-console
  template:
    metadata:
      labels:
        app: admin-console
    spec:
      containers:
      - name: admin-console
        image: schniebel/admin:29c57008f0dd81dcee84d6a0fcff3c64cc1333ab
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/arch: arm64