apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-console
  template:
    metadata:
      labels:
        app: admin-console
    spec:
      containers:
      - name: admin-console
        image: schniebel/admin:efa9551fd7afb1e3be852509633081803aebd3d2
        ports:
        - containerPort: 80