apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-console
  template:
    metadata:
      labels:
        app: admin-console
    spec:
      containers:
      - name: admin-console
        image: schniebel/admin:34e0750479a308527f9b70d1a155f1e8d4b0cb4c
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/arch: arm64