apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-console
  template:
    metadata:
      labels:
        app: admin-console
    spec:
      containers:
      - name: admin-console
        image: schniebel/admin:7524c8c1f57c29472cf0617c9bca65143cd72f30
        ports:
        - containerPort: 80