apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-console
  template:
    metadata:
      labels:
        app: admin-console
    spec:
      containers:
      - name: admin-console
        image: schniebel/admin:7a624fb5487fea2383708c1351ac37065f81c8f0
        ports:
        - containerPort: 80