apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-console
  template:
    metadata:
      labels:
        app: admin-console
    spec:
      containers:
      - name: admin-console
        image: schniebel/admin:e579474aa586dce8ebfacf8508d7346b3af66356
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/arch: arm64