apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-console
  template:
    metadata:
      labels:
        app: admin-console
    spec:
      containers:
      - name: admin-console
        image: schniebel/admin:3cd86102398aee7825d0a44c60f9a5b6f080ae65
        ports:
        - containerPort: 80