apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: schniebel/admin:05b8c44e5b9bdebf1ab5cd15eaaea4db09f56cff
        ports:
        - containerPort: 80