apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: schniebel/admin:91ab97c4f509de206003773301a51abb1dadd92e
        ports:
        - containerPort: 80