apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: schniebel/admin:919cb4b281219b0f204ea8404695dddf993ce20d
        ports:
        - containerPort: 80