apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: schniebel/admin:86a800df4da816832a66a3e48ebec7482c3359ab
        ports:
        - containerPort: 80