apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/cloudflare-tunnel
      version:  0.3.0
      sourceRef:
        kind: GitRepository
        name: cloudflare-tunnel
        namespace: flux-system
  interval: 1m
  values:
    cloudflare:
      tunnelName: "ryanschnabel-com"
      tunnelId: "5b95e788-4f87-4c50-be9d-64cfa67bf0a6"
      secretName: tunnel-credentials
    ingress:
      - hostname: ryanschnabel.com
        service: http://traefik.kube-system.svc.cluster.local:80