apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/cloudflare-tunnel
      version:  0.3.0
      sourceRef:
        kind: GitRepository
        name: cloudflare-tunnel
        namespace: flux-system
  interval: 1m
  values:
    cloudflare:
      tunnelName: "ryanschnabel-tunnel"
      tunnelId: "dac35fb2-3e79-482a-9817-530d9f53a0d2"
      secretName: tunnel-credentials
    ingress:
      - hostname: longhorn.ryanschnabel.com
        service: longhorn-frontend.longhorn-system.svc.cluster.local:80