# Secrets
#
# Kubernetes requires secret values to be converted to base64 when defined
# explicitly like this. (use `echo -n 'secret-value' | base64`)

apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-credentials
  namespace: monitoring
type: Opaque
data:
  GF_AUTH_GOOGLE_CLIENT_ID: <encrypted client id here>
  GF_AUTH_GOOGLE_CLIENT_SECRET: <encrypted client secret>

##here you dont have to encrypt
kubectl create secret generic grafana-oauth-credentials \
  --from-literal=GF_AUTH_GOOGLE_CLIENT_ID='' \
  --from-literal=GF_AUTH_GOOGLE_CLIENT_SECRET=''