apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: ./deploy/charts/rook-ceph-cluster
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: rook-ceph
        namespace: flux-system
  interval: 1m
  values:
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v18.2