apiVersion: v1
kind: Service
metadata:
  name: admin-console
  namespace: admin
spec:
  selector:
    app: admin-console
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP