apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ryanschnabel-io
  namespace: default
spec:
  secretName: ryanschnabel-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "** domain here **"
  dnsNames:
  - "** domain here **"
