apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryanschnabel
  namespace: ryanschnabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryanschnabel
  template:
    metadata:
      labels:
        app: ryanschnabel
    spec:
      containers:
      - name: ryanschnabel
        image: schniebel/ryanschnabel-com:d2b5fd5ce18e507d1848bd1b6e9daf37a646e4f9
        ports:
        - containerPort: 80