apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryanschnabel
  namespace: ryanschnabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryanschnabel
  template:
    metadata:
      labels:
        app: ryanschnabel
    spec:
      containers:
      - name: ryanschnabel
        image: schniebel/ryanschnabel-com:b512164a75259103c9f7ad528f3c210b9b250157
        ports:
        - containerPort: 80