apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-system
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/default/traefik-forward-auth
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m

---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./resources/