apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryanschnabel
  namespace: ryanschnabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryanschnabel
  template:
    metadata:
      labels:
        app: ryanschnabel
    spec:
      containers:
      - name: ryanschnabel
        image: docker.io/schniebel/ryanschnabel-com:1712665409 # {"$imagepolicy": "flux-system:ryanschnabel-com"}
        ports:
        - containerPort: 80