apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryanschnabel
  namespace: ryanschnabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryanschnabel
  template:
    metadata:
      labels:
        app: ryanschnabel
    spec:
      containers:
      - name: ryanschnabel
        image: schniebel/ryanschnabel-com:4563a44d73c9568803886a3d529f6357284694d3 # {"$imagepolicy": "flux-system:ryanschnabel-com"}
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/arch: arm64