apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryanschnabel
  namespace: ryanschnabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryanschnabel
  template:
    metadata:
      labels:
        app: ryanschnabel
    spec:
      containers:
      - name: ryanschnabel
        image: schniebel/ryanschnabel-com:231c24ae6b5f54acb1838c36492cd693a992108f # {"$imagepolicy": "flux-system:ryanschnabel-com"}
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/arch: arm64