apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/oauth2-proxy/manifests
  ref:
    branch: main