# Example to generate new username and password:
#   htpasswd -nB username | tee auth-string


apiVersion: v1
kind: Secret
metadata:
  name: auth-secret

data:
  users: |
    ****encoded password hash here****
