apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: **base064 encoded password here***
  GF_SECURITY_ADMIN_USER: **base064 encoded username here***
