apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: welcome-nginx-ingressroute
spec:
  routes:
  - kind: Rule
    match: Host(`ryanschnabel.com`)
    services:
    - kind: Service
      name: welcome-nginx-svc-prod
      port: 80
  - kind: Rule
    match: Host(`test.ryanschnabel.com`)
    middlewares:
      - name: nginx-basic-auth
    services:
    - kind: Service
      name: welcome-nginx-svc-test
      port: 80
  - kind: Rule
    match: Host(`dashboard.ryanschnabel.com`)
    middlewares:
      - name: nginx-basic-auth
    services:
    - kind: TraefikService
      name: api@internal
  tls:
    secretName: ryanschnabel-io-tls
    domains:
    - main: ryanschnabel.com
      sans:
      - test.ryanschnabel.com
      - dashboard.ryanschnabel.com
