apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-nginx-test
spec:
  selector:
    matchLabels:
      app: welcome-nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        app: welcome-nginx-test
    spec:
      containers:
        - image: schniebel/welcome-page:{TAG}
          name: welcome-nginx-test
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
       - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: welcome-nginx-svc-test
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: welcome-nginx-test
    
---
 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: welcome-nginx-ingress-test
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "test.ryanschnabel.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: welcome-nginx-svc-test
            port:
              number: 80
  tls:
  - hosts:
      - ryanschnabel.io
    secretName: ryanschnabel-io-tls



apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: welcome-nginx-ingressroute-test
spec:
  routes:
  - kind: Rule
    match: Host(`test.ryanschnabel.io`)
#    priority: 10                    # [4]
#    middlewares:                    # [5]
#    - name: middleware1             # [6]
#      namespace: default            # [7]
    services:                       # [8]
    - kind: Service
      name: welcome-nginx-svc-test
#      namespace: default
#      passHostHeader: true
      port: 80                      # [9]
#      responseForwarding:
#        flushInterval: 1ms
      scheme: https
#      serversTransport: transport   # [10]
#      sticky:
#        cookie:
#          httpOnly: true
#          name: cookie
#          secure: true
 #         sameSite: none
 #     strategy: RoundRobin
 #     weight: 10
  tls:
    secretName: ryanschnabel-io-tls
    options:                        # [13]
      name: opt                     # [14]
      namespace: default            # [15]
    certResolver: foo               # [16]
    domains:                        # [17]
    - main: test.ryanschnabel.io
#      sans:
#      - a.example.net
#      - b.example.net

