apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-nginx-test
spec:
  selector:
    matchLabels:
      app: welcome-nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        app: welcome-nginx-test
    spec:
      containers:
        - image: schniebel/welcome-page:{TAG}
          name: welcome-nginx-test
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
       - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: welcome-nginx-svc-test
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: welcome-nginx-test
    
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: welcome-nginx-ingressroute-test
spec:
  routes:
  - kind: Rule
    match: Host(`test.ryanschnabel.io`)
    services:
    - kind: Service
      name: welcome-nginx-svc-test
      port: 80
