apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-sso
  labels:
    app: traefik-sso
spec:
  selector:
    matchLabels: 
      app: traefik-sso
  template:
    metadata:
      labels:
        name: traefik-sso
        app: traefik-sso
    spec:
      containers:
      - name: traefik-sso
        image: npawelek/traefik-forward-auth
        imagePullPolicy: Always
        env:
        - name: PROVIDERS_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: traefik-sso
              key: traefik-forward-auth-google-client-id
        - name: PROVIDERS_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-sso
              key: traefik-forward-auth-google-client-secret
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-sso
              key: traefik-forward-auth-secret
        - name: COOKIE_DOMAIN
          value: ryanschnabel.io
        - name: AUTH_HOST
          value: auth.ryanschnabel.io
        - name: INSECURE_COOKIE
          value: "false"
        - name: URL_PATH 
          value: /_oauth
        - name: WHITELIST
          value: ryan.d.schnabel@gmail.com
        - name: LOG_LEVEL
          value: debug
        ports:
        - containerPort: 4181
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-sso
spec:
  selector:
    app: traefik-sso
  ports:
  - protocol: TCP
    port: 4181
    targetPort: 4181
