apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 190Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/general
    server: 10.128.0.16 # VM internal IP
  persistentVolumeReclaimPolicy: Retain