apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 170Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/nfs/general
    server: 10.128.0.20 # VM internal IP
  persistentVolumeReclaimPolicy: Retain