apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: source-controller
    app.kubernetes.io/part-of: kube-prometheus
  name: source-controller
  namespace: monitoring
spec:
  endpoints:
  - port: "metrics"
    interval: 30s
  namespaceSelector:
    matchNames:
    - flux-system
  selector:
    matchLabels:
      app: source-controller