apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-plex
  namespace: kube-plex
spec:
  chart:
    spec:
      chart: ./charts/kube-plex
      version: 0.2.7
      sourceRef:
        kind: GitRepository
        name: kube-plex
        namespace: flux-system
  interval: 1m
  values:
    image:
      repository: maxlbch/pms-docker-arm64
      tag: latest
    kubePlex:
      repository: lucashalbert/kube-plex
      tag: arm64v8-alpha-0.0.1
    nodeSelector:
      beta.kubernetes.io/arch: arm64

    persistence:
      transcode:
        # Optionally specify claimName to manually override the PVC to be used for
        # the transcode directory. If claimName is specified, storageClass and size
        # are ignored.
        ## claimName: "plex-transcode-pvc"
        # Optionally specify a storage class to be used for the transcode directory.
        # If not specified and claimName is not specified, the default storage
        # class will be used.
        storageClass: ""
        # subPath: some-subpath
        # The requested size of the volume to be used when creating a
        # PersistentVolumeClaim.
        size: 20Gi
        # Access mode for this volume
        accessMode: ReadWriteMany
      data:
        # Optionally specify claimName to manually override the PVC to be used for
        # the data directory. If claimName is specified, storageClass and size are
        # ignored.
        ## claimName: "plex-data-pvc"
        # Optionally specify a storage class to be used for the data directory.
        # If not specified and claimName is not specified, the default storage
        # class will be used.
        storageClass: ""
        # subPath: some-subpath
        # The requested size of the volume to be used when creating a
        # PersistentVolumeClaim.
        size: 40Gi
        # Access mode for this volume
        accessMode: ReadWriteMany
      extraData: []
        # Optionally specifify additional Data mounts.  These will be mounted as
        # /data-${name}.  This should be in the same format as the above 'data', 
        # with the additional field 'name'
        # - claimName: "special-tv"
        #   name: 'foo'

      config:
        # Optionally specify claimName to manually override the PVC to be used for
        # the config directory. If claimName is specified, storageClass and size
        # are ignored.
        ## claimName: "plex-config-pvc"
        # Optionally specify a storage class to be used for the config directory.
        # If not specified and claimName is not specified, the default storage
        # class will be used.
        # subPath: some-subpath
        storageClass: ""
        # The requested size of the volume to be used when creating a
        # PersistentVolumeClaim.
        size: 20Gi
        # Access mode for this volume
        accessMode: ReadWriteMany