baseURL = "https://admin.ryanschnabel.com/"
languageCode = "en-us"
theme = "glim-midnight"

[params]
    title = "Ryan Schnabel"
    phrases = ["Admin", "Console"]
    links = [
    {name = "Landing", url = "https://ryanschnabel.com"},    
    {name = "Traefik", url = "https://dashboard.ryanschnabel.com"},    
    {name = "Monitoring", url = "https://monitoring.ryanschnabel.com/"},    
    {name = "Github, url = "https://github.com/schniebel/ryanschnabel-com"}     
    ] 
    background = "bg.mp4"