kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-transcode-pvc
  namespace: kube-plex
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-data-pvc
  namespace: kube-plex
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config-pvc
  namespace: kube-plex
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi