apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus
  interval: 1m
  path: ./clusters/default/monitoring/alertmanager
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m