apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/grafana/helm-charts
  ref:
    branch: main