apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: ./charts/loki-stack
      version: 2.9.10
      sourceRef:
        kind: GitRepository
        name: grafana
        namespace: flux-system
  interval: 1h