apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-bff
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-bff
  template:
    metadata:
      labels:
        app: admin-bff
    spec:
      containers:
      - name: admin-bff
        image: docker.io/schniebel/admin-bff:1712087291 # {"$imagepolicy": "flux-system:admin-bff"}
        ports:
        - containerPort: 80
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key-secret
              key: API_KEY
        - name: DOMAIN
          value: "api.ryanschnabel.io"
      nodeSelector:
        kubernetes.io/arch: arm64
