apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn-system
  namespace: longhorn-system
spec:
  install:
    timeout: 10m  # Increase this as necessary
  upgrade:
    timeout: 10m  # Increase this as necessary
  chart:
    spec:
      chart: ./charts/longhorn
      version:  1.5.3
      sourceRef:
        kind: GitRepository
        name: longhorn-system
        namespace: flux-system
  interval: 1m