apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  volumeMode: Block
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 34.136.110.15:3260
    iqn: iqn.2022-12.com.ryanschnabel:target1
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: iscsi-secret