apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-console
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-console
  template:
    metadata:
      labels:
        app: admin-console
    spec:
      containers:
      - name: admin-console
        image: docker.io/schniebel/admin:1712087253 # {"$imagepolicy": "flux-system:admin"}
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/arch: arm64
