apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: monitoring-ingressroute
  namespace: monitoring
spec:
  routes:
  - kind: Rule
    match: Host(`monitoring.ryanschnabel.com`)
    services:
    - kind: Service
      name: grafana
      port: 3000