apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  chart:
    spec:
      chart: ./charts/plex-media-server
      version: 0.1.8
      sourceRef:
        kind: GitRepository
        name: plex
        namespace: flux-system
  interval: 1m
  values:
    image:
      repository: maxlbch/pms-docker-arm64
      tag: latest
    nodeSelector:
      kubernetes.io/hostname: slave1
    pms:
      configStorage: 600Gi