apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: <encrypted password here>
  GF_SECURITY_ADMIN_USER: <encrypted user here>

