apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: U3VwZXJkcmFuazE2
  GF_SECURITY_ADMIN_USER: c2NobmllYmVs

