apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-data-dir-pvc
  namespace: monitoring
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
