apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-db-openebs-pvc
  namespace: monitoring
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
