apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
  ref:
    branch: master