apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/prometheus-community/helm-charts
  ref:
    branch: main