apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  chart:
    spec:
      chart: ./charts/alertmanager
      version: 1.7.0
      sourceRef:
        kind: GitRepository
        name: alertmanager
        namespace: flux-system
  interval: 1h
  values:
    nodeSelector:
      kubernetes.io/hostname: prometheus
    extraSecretMounts:
      - name: slack-token
        mountPath: /etc/alertmanager/slack
        secretName: slack-token
        readOnly: true
    extraInitContainers:
      - name: token-injector
        image: alpine:latest
        command: ['sh', '-c', 'cp /etc/alertmanager/alertmanager.yml /tmp/alertmanager.yml && sed -i "s|<YOUR_SLACK_TOKEN>|$(cat /etc/alertmanager/slack/token)|" /tmp/alertmanager.yml && mv /tmp/alertmanager.yml /etc/alertmanager/alertmanager.yml']
        volumeMounts:
          - name: config
            mountPath: /etc/alertmanager
          - name: slack-token
            mountPath: /etc/alertmanager/slack
    config:
      route:
        receiver: 'slack-notifications'
      receivers:
        - name: slack-notifications
          slack_configs:
            - api_url: 'https://slack.com/api/chat.postMessage'
              channel: '#monitoring'
              send_resolved: true
              bearer_token: '<YOUR_SLACK_TOKEN>'