apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  chart:
    spec:
      chart: ./charts/alertmanager
      version: 1.7.0
      sourceRef:
        kind: GitRepository
        name: alertmanager
        namespace: flux-system
  interval: 1h
  values:
    nodeSelector:
      kubernetes.io/hostname: prometheus
    config:
      global:
        slack_api_url: 'https://hooks.slack.com/services/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'
      route:
        receiver: 'slack-notifications'
      receivers:
        - name: slack-notifications
          slack_configs:
            - channel: '#monitoring'
              send_resolved: true