name: Admin Deployment

on:
  push:
    branches:
      - main
    paths:
      - admin/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Update submodules
        run: git submodule update --init --recursive
        working-directory: ryanschnabel-com

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./admin
          file: ./admin/Dockerfile
          push: true
          tags: schniebel/admin:${{ github.sha }}
          platforms: linux/arm64
      
      - name: Update deployment.yaml with new image tag
        run: |
          sed -i 's|schniebel/admin:.*|schniebel/admin:'${{ github.sha }}'|' ./clusters/default/admin/console/deployment-admin-console.yaml
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<github-actions@github.com>"
          git add .
          git commit -m "Update admin console image tag in deployment-admin-console.yaml to ${{ github.sha }}"
          git push