name: ryanschnabel API Deployment

on:
  push:
    branches:
      - main
    paths:
      - api/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Update submodules
        run: git submodule update --init --recursive
        working-directory: api

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: schniebel/ryanschnabel-api:${{ github.sha }}
          platforms: linux/arm64

      - name: Pull latest changes from the repository
        run: git pull origin main
              
      - name: Update deployment.yaml with new image tag
        run: |
          sed -i 's|schniebel/ryanschnabel-api:.*|schniebel/ryanschnabel-api:'${{ github.sha }}'|' ./clusters/default/api/deployment.yaml
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<github-actions@github.com>"
          git add .
          git commit -m "Update api image tag in deployment.yaml to ${{ github.sha }}"
          git push