name: ryanschnabel API Deployment

on:
  push:
    branches:
      - main
    paths:
      - api/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Update submodules
        run: git submodule update --init --recursive
        working-directory: api

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Get Unix timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: schniebel/ryanschnabel-api:${{ steps.timestamp.outputs.timestamp }}
          platforms: linux/arm64