name: ryanschnabel-com Deployment

on:
  push:
    branches:
      - main
    paths:
      - hugo/**

jobs:
  build:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build and push Docker image
      run: |
        docker build -t schniebel/ryanschnabel-com:${{ github.sha }} .
        docker push schniebel/ryanschnabel-com:${{ github.sha }}

    - name: Update deployment.yaml with new image tag
      run: |
        ssed -i 's|schniebel/ryanschnabel-com:.*|schniebel/ryanschnabel-com:'${{ github.sha }}'|' ./clusters/default/ryanschnabel/deployment.yaml

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<github-actions@github.com>"
        git add deployment.yaml
        git commit -m "Update ryanschnabel image tag in deployment.yaml to ${{ github.sha }}"
        git push