name: Deployment CI

on:
  push:
    branches: [ "main" ]

jobs:

  Build:
    name: Build Docker Image
    runs-on: ubuntu-latest   
    
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker Build
      run: |
        docker build -t schniebel/welcome-page:${{ github.sha }} .
    - name: Docker Push
      run: |
        docker push schniebel/welcome-page:${{ github.sha }}

  Deploy:
    name: Deploy Docker Image To Kubernetes Cluster
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Create Kubeconfig
      run: | 
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
    - name: Use Context
      run: kubectl config use-context default
    - name: Deploy to Cluster
      run: kubectl apply -f config/kubernetes.yaml
    
