name: Deployment CI

on:
  push:
    branches: [ "main" ]

jobs:

  Build:
    name: Build Docker Image
    runs-on: ubuntu-latest   
    
    steps:
    - uses: actions/checkout@v2
    - name: Create Kubeconfig
      run: | 
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
