name: Deployment CI

on:
  push:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/arm64/v8
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/welcome-page:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
