name: Deployment CI

on:
  push:
    branches: [ "main" ]

jobs:

  Build:
    name: Build Docker Image
    runs-on: ubuntu-latest   
    
    steps:
    - uses: actions/checkout@v2
    - name: Create Kubeconfig
      run: | 
        mkdir ${HOME}/.kube
    - name: Use Context
      run: kubectl config use-context default
    - name: Deploy to Cluster
      run: kubectl apply -f config/kubernetes.yaml
