name: DOD:S pipeline

on:
  push:
    branches:
      - main
    paths:
      - game-server/dods/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get Unix timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./game-server/dods
          file: ./game-server/dods/Dockerfile
          push: true
          tags: schniebel/dods-gameserver:${{ steps.timestamp.outputs.timestamp }}

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}
