apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kibana
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  interval: 1h
  values:
    nodeSelector:
      kubernetes.io/hostname: prometheus