apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      type: nfs
  storageClassName: ""  # Explicitly set to not use a storage class