apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      type: nfs-graf-pv
  storageClassName: "nfs-client"