apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
  selector:
    matchLabels:
      type: nfs-prom-pv
  storageClassName: "nfs-client"