apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi