apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany  # Changed from ReadWriteOnce to ReadWriteMany
  resources:
    requests:
      storage: 60Gi
  selector:
    matchLabels:
      type: nfs