apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-setup
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-persistence
  interval: 1m
  path: ./clusters/default/monitoring/setup
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m